module.exports = {
  parser: "babel-eslint",
  ecmaFeatures: {
    "classes": true,
    "modules": true,
    "experimentalObjectRestSpread": true,
    "jsx": true
  },
  rules: {
    "eqeqeq": 2,
    "no-multi-spaces": 2,
    "no-unused-vars": 2,
    "no-shadow": 2,
    "no-console": 2,
    "no-debugger": 2,
    "no-empty": 2,
    "no-irregular-whitespace": 2,
    "no-sparse-arrays": 2,
    "no-unexpected-multiline": 2,
    "no-unreachable": 2,
    "valid-typeof": 2,
    "block-scoped-var": 2,
    "consistent-return": 2,
    "curly": 2,
    "dot-location": [2, "property"],
    "dot-notation": [2, {"allowPattern": "^[a-z]+(_[a-z]+)+$"}],
    "no-param-reassign": [2, {"props": true}],
    "no-redeclare": 2,
    "no-unused-expressions": [2, {"allowShortCircuit": true, "allowTernary": true}],
    "vars-on-top": 2,
    "yoda": [2, "never", {"exceptRange": true}],
    "no-lonely-if": 2,
    "no-constant-condition": 2,
    "no-dupe-class-members": 2,
    "no-var": 2,
    "object-shorthand": [2, "always"],
    "prefer-arrow-callback": 2,
    "prefer-const": 2,
    "prefer-spread": 2,
    "prefer-template": 2,
    "strict": 0,
    "no-dupe-keys": 2,
    "no-underscore-dangle": 0,
    "no-undef": 2,
    "max-lines": 2,
    "react/jsx-boolean-value": [2, "always"],
    "react/jsx-indent-props": [2, 2],
    "react/jsx-no-duplicate-props": [2, { "ignoreCase": true }],
    "react/jsx-no-undef": 2,
    "react/jsx-no-bind": [2, { "ignoreRefs": true }],
    "react/sort-prop-types": 2,
    "react/jsx-sort-props": 2,
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/prefer-stateless-function": 2,
    "react/no-unused-prop-types": [2, { "skipShapeProps": true }],
    "react/no-did-mount-set-state": 2,
    "react/no-did-update-set-state": 2,
    "react/no-direct-mutation-state": 2,
    "react/no-multi-comp": 2,
    "react/no-unknown-property": 2,
    "react/prop-types": 2,
    "react/react-in-jsx-scope": 2,
    "import/extensions": ["error", {"js": "never", "jsx": "never"}],
    "react/self-closing-comp": 2,
    "react/sort-comp": 2
  },
  "plugins": [
    "react",
    "import"
  ],
  "globals": {
    "require": false,
    "document": false,
    "window": false,
    "confirm": false,
    "screen": false,
    "NODE_ENV": false,
    "Promise": false,
    "console": false,
    "module": false,
    "process": false,
    "describe": false,
    "before": false,
    "it": false,
  }
}
